//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barbershop.ApllicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarbershopEntities : DbContext
    {
        public static BarbershopEntities _context;
        public BarbershopEntities()
            : base("name=BarbershopEntities")
        {
        }
    
        public static BarbershopEntities GetContext()
        {
            if (_context == null)
                _context = new BarbershopEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barber> Barber { get; set; }
        public virtual DbSet<Recording> Recording { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Work> Work { get; set; }
        public virtual DbSet<RecordingWork> RecordingWork { get; set; }
    }
}
