//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barbershop.ApllicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barber
    {
        public int ID { get; set; }
        public string FIOMaster { get; set; }
        public string Age { get; set; }
        public string HaircutStyle { get; set; }
        public string NumberMaster { get; set; }
    }
}
