//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barbershop.ApllicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordingWork
    {
        public int ID { get; set; }
        public string NumberWork { get; set; }
        public string Date { get; set; }
        public string FIO { get; set; }
    }
}
